app/chat/__init__.py
from flask import Blueprint


bp = Blueprint("chat", __name__)

from app.chat import views

app/chat/views.py
from flask import request, jsonify, render_template
from flask_login import login_required, current_user
from app import pusher, db
from app.chat import bp as chat_bp
from app.models import User, Channel, Message


@chat_bp.route("/")
@chat_bp.route("/<username>")
def chat(username=None):
    recipient = None
    if username:
        recipient = User.query.filter_by(username=username).first()
    return render_template("chat/chat.html", recipient=recipient)


@chat_bp.route('/request_chat', methods=["POST"])
@login_required
def request_chat():
    data = request.json
    recipient_id = data["recipient_id"]
    sender_id  = current_user.id
    sender_chat_channel = f"private-chat_user_{sender_id}"
    recipient_chat_channel = f"private-chat_user_{recipient_id}"
    
    # get channel between sender, recipient if exists
    # create otherwise
    channel = Channel.get_or_create(sender_id, recipient_id)

    data = {
        "sender_id": sender_id,
        "recipient_id": recipient_id,
        "sender_chat_channel": sender_chat_channel,
        "recipient_chat_channel": recipient_chat_channel,
        "channel_name": channel.name,
        "channel_id": channel.id,
    }
    # trigger an event to recipient
    pusher.trigger(recipient_chat_channel, "new_chat", data)

    return jsonify(data)

@chat_bp.route('/send_message', methods=["POST"])
@login_required
def send_message():
    data = request.json
    sender_id = data["sender_id"]
    recipient_id = data["recipient_id"]
    message = data["message"]
    channel = data["channel"]
    
    channelObj = Channel.query.get(channel)
    new_message = Message(body=message, channel_id=channel)
    new_message.sender_id = sender_id
    new_message.recipient_id = recipient_id
    db.session.add(new_message)
    db.session.commit()

    data["channel_name"] = channelObj.name
    # message html is used in chat box
    # It will have different styles for sender, recipient
    # So We need to render for each user separatly
    data["message"] = render_template("chat/message.html", message=new_message, user_id=recipient_id)
    
    # send the message to recipient via pusher
    pusher.trigger(channelObj.name, 'new_message', data)
    
    # send message back to sender via HTTP response
    data["message"] = render_template("chat/message.html", message=new_message, user_id=sender_id)
    return jsonify(data)

@chat_bp.route('/get_message/<channel_id>')
@login_required
def get_messages(channel_id):
    messages = Message.query.filter_by(channel_id=channel_id).all()

    return jsonify([ render_template("chat/message.html", message=message, user_id=current_user.id) for message in messages])

@chat_bp.route("/pusher/auth", methods=['POST'])
@login_required
def pusher_authentication():
    channel_name = request.form.get('channel_name')
    socket_id = request.form.get('socket_id')

    auth = pusher.authenticate(
        channel=channel_name,
        socket_id=socket_id
    )

    return jsonify(auth)

app/templates/chat/chat.html
{% extends "base.html" %}

{% block css %}
    <link href="{{ url_for('static', filename='css/chat.css') }}" rel="stylesheet"> 
{% endblock css %}

{% block content %}
    <div class="container">
        <h1>Messages</h1>
        <div class="row">
            <div class="col-md-2 chat-users min-height-500">
                {% for user in current_user.followed %}
                    <div class="chat-users__item {{ 'chat-user-active' if recipient is not none and recipient == user }}">
                        <img src="{{ user.avatar(40) }}" class="chat-user__image" />
                        <a href="{{ url_for('chat.chat', username=user.username) }}">{{ user.username }}</a><br>
                    </div>
                {% endfor %}
            </div>
            {% if recipient is not none %}
            <div class="col-md-10 min-height-500">
                <div id="messages" class="messages-container"></div>
                <div class="message-area">
                    <input type="text" id="messagebox" placeholder=" message {{ recipient.username }}"/>
                    <button onclick="sendMessage()" class="send-button">Send</button>
                </div>
            </div>
            {% else %}
                <div class="col-md-10 min-height-500">
                    <div class="messages-container-dummy">
                        <p>Click on any of your connections to start conversation....</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block js_scripts %}
    {% if recipient %}
    <script>
        let channelID = null;
        let channelName = null;
        let currentChatChannel = null;
        let senderChatChannel = null;
        let recipientChatChannel = null;
        let senderID = {{ current_user.id }}
        let currentUserID = senderID
        let recipientID = {{ recipient.id }}

        let pusher = new Pusher('04587cc4f2fd0ca4213c', {
                cluster: 'ap2',
                forceTLS: true,
                authEndpoint: "/chat/pusher/auth"
            });
        
        $(function(){
            const personalChannel = pusher.subscribe(`private-chat_user_${senderID}`)
            personalChannel.bind("new_chat", function(data){
                const isSubscribed = pusher.channel(data.channel_name)
                if(!isSubscribed){
                    let one_on_one_chat = subscribeChatChannel(data.channel_name)
                }
            })

            $( "input#messagebox" ).keydown(function( event ) {
                if ( event.which == 13 ) {
                    sendMessage();
                }
            });

            (function requestChat(){
                $.ajax({
                    url: "/chat/request_chat",
                    method: "POST",
                    dataType: 'json',
                    contentType: 'application/json',
                    data: JSON.stringify({
                        recipient_id: recipientID,
                    })
                }).done(function(data){
                    channelID = data.channel_id
                    channelName = data.channel_name;
                    currentChatChannel = data.channel_name;
                    senderChatChannel = data.sender_chat_channel;
                    recipientChatChannel = data.recipient_chat_channel

                    getMessagesInChannle();
                    const isSubscribed = pusher.channel(data.channel_name)
                    if(!isSubscribed){
                        let one_on_one_chat = subscribeChatChannel(data.channel_name)
                    }
                })
            })();
    
        })

        function getMessagesInChannle(){
            $.ajax({
                url: `/chat/get_message/${channelID}`,
                method: 'GET',
                dataType: 'json',
                contentType: 'application/json',
            }).done(function(data){
                data.forEach(function(message){
                    $('#messages').append(message)
                })
                scrollToBottom();
            })
        }


        function subscribeChatChannel(channelName) {
            var channel = pusher.subscribe(channelName);
            channel.bind('new_message', function (data) {
                if(data.channel_name === currentChatChannel && currentUserID === data.recipient_id){
                    $('#messages').append(data.message);
                    scrollToBottom();
                }
            });
            return channel
        }

        function sendMessage(event){
            let message = $('input#messagebox').val()
            $.ajax({
                url: '/chat/send_message',
                method: 'POST',
                dataType: 'json',
                contentType: 'application/json',
                data: JSON.stringify({
                    channel : channelID,
                    message : message,
                    sender_id: {{ current_user.id }},
                    recipient_id : {{ recipient.id }},
                })
            }).done(function(data){
                $('input#messagebox').val("")
                $('#messages').append(data.message);
                scrollToBottom();
            })
        }

        function scrollToBottom() {
            $('#messages').animate({scrollTop: $('#messages').prop('scrollHeight')});
        };

    </script>
    {% endif %}
{% endblock js_scripts %}

app/templates/chat/message.html
{% if message.sender_id == user_id %}
<div class=" msg msg_right">
    <p class="mr-0"><span style="background: #4f9fff;" class="msg_container">{{ message.body }}</span></p>
    <img src="{{ message.sender.avatar(36)}}" class="msg-avatar">
</div>
{% else %}
<div class="msg msg_left">
    <img src="{{ message.sender.avatar(36)}}" class="msg-avatar">
    <p class="mr-0"><span style="background: #deefff; color: black;" class="msg_container">{{ message.body }}</span></p>
</div>
{% endif %}